import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

const sidebars: SidebarsConfig = {
	tutorialSidebar: [
		{
			type: "category",
			label: "始めよう",
			items: [
				"getting-started/what-is-careti",
				"getting-started/model-selection-guide",
				"getting-started/installing-careti",
				"getting-started/selecting-your-model",
				"getting-started/your-first-project",
				"getting-started/task-management",
				"getting-started/understanding-context-management",
				{
					type: "category",
					label: "For New Coders",
					items: ["getting-started/for-new-coders", "getting-started/installing-dev-essentials"],
				},
			],
		},
		{
			type: "category",
			label: "紹介",
			items: ["introduction/welcome", "introduction/overview"],
		},
		{
			type: "category",
			label: "^ Caret独占機能",
			items: [
				{ type: "doc", id: "caret-exclusive/persona-system", label: "^ ペルソナシステム" },
				{ type: "doc", id: "caret-exclusive/dual-prompt-modes", label: "^ デュアルモードシステム" },
				{ type: "doc", id: "caret-exclusive/brand-switching", label: "^ OEMブランドカスタマイズ" },
				{ type: "doc", id: "caret-exclusive/enhanced-provider-setup", label: "^ 強化されたプロバイダー設定" },
				{ type: "doc", id: "caret-exclusive/caret-provider", label: "^ Caretプロバイダー" },
				{ type: "doc", id: "caret-exclusive/knowledge-parity-system", label: "^ AI組織知識とルール標準化" },
				{ type: "doc", id: "caret-exclusive/document-tools", label: "^ ドキュメント読み取りツール" },
				{ type: "doc", id: "caret-exclusive/image-tools", label: "^ イメージツール" },
				{ type: "doc", id: "caret-exclusive/multilingual-ui", label: "^ 完全な多言語UI" },
			],
		},
		{
			type: "category",
			label: "プロンプトスキルの向上",
			items: ["prompting/prompt-engineering-guide", "prompting/caret-memory-bank"],
		},
		{
			type: "category",
			label: "モデル設定",
			items: [
				"core-features/model-selection-guide",
				"model-config/model-comparison",
				"model-config/context-windows",
			],
		},
		{
			type: "category",
			label: "機能",
			items: [
				{
					type: "doc",
					id: "caret-exclusive/persona-system",
					label: "^ ペルソナシステム",
				},
				{
					type: "doc",
					id: "caret-exclusive/dual-prompt-modes",
					label: "^ デュアルモードシステム",
				},
				{
					type: "doc",
					id: "features/input-history",
					label: "^ プロンプト履歴",
				},
				{
					type: "doc",
					id: "caret-exclusive/brand-switching",
					label: "^ OEMブランド切替",
				},
				{
					type: "doc",
					id: "caret-exclusive/enhanced-provider-setup",
					label: "^ 強化されたプロバイダー設定",
				},
				{
					type: "doc",
					id: "caret-exclusive/caret-provider",
					label: "^ Caretプロバイダー",
				},
				{
					type: "doc",
					id: "caret-exclusive/knowledge-parity-system",
					label: "^ AI組織知識とルール標準化",
				},
				{
					type: "doc",
					id: "caret-exclusive/document-tools",
					label: "^ ドキュメントツール",
				},
				{
					type: "doc",
					id: "caret-exclusive/image-tools",
					label: "^ 画像ツール",
				},
				{
					type: "doc",
					id: "caret-exclusive/multilingual-ui",
					label: "^ 多言語UI",
				},
				"features/skills",
				"features/yolo-mode",
				"features/dictation",
				"features/multiroot-workspace",
				"features/drag-and-drop",
				"features/focus-chain",
				"features/plan-and-act",
				"features/auto-compact",
				"features/auto-approve",
				"features/checkpoints",
				"features/caret-rules",
				"features/editing-messages",
				"features/markdown-rendering",
				"features/hooks",
				"features/claude-code-compatibility",
				{
					type: "category",
					label: "@ メンション",
					items: [
						"features/at-mentions/overview",
						"features/at-mentions/file-mentions",
						"features/at-mentions/folder-mentions",
						"features/at-mentions/git-mentions",
						"features/at-mentions/problem-mentions",
						"features/at-mentions/terminal-mentions",
						"features/at-mentions/url-mentions",
					],
				},
				{
					type: "category",
					label: "スラッシュコマンド",
					items: [
						"features/slash-commands/slash-commands",
						"features/slash-commands/deep-planning",
						"features/slash-commands/new-rule",
						"features/slash-commands/new-task",
						"features/slash-commands/report-bug",
						"features/slash-commands/smol",
						"features/slash-commands/workflows",
						"features/slash-commands/workflows/quickstart",
						"features/slash-commands/workflows/best-practices",
					],
				},
				{
					type: "category",
					label: "コマンドとショートカット",
					items: [
						"features/commands-and-shortcuts/overview",
						"features/commands-and-shortcuts/code-commands",
						"features/commands-and-shortcuts/git-integration",
						"features/commands-and-shortcuts/keyboard-shortcuts",
						"features/commands-and-shortcuts/terminal-integration",
					],
				},
				{
					type: "category",
					label: "カスタマイズ",
					items: [
						"features/customization/opening-caret-in-sidebar",
						"features/customization/disable-terminal-pagers",
					],
				},
				{
					type: "category",
					label: "タスク",
					items: ["features/tasks/understanding-tasks", "features/tasks/task-management"],
				},
			],
		},
		/* Careti CLI hidden for v0.4.4.
		{
			type: "category",
			label: "Careti CLI",
			items: [
				"caret-cli/overview",
				"caret-cli/installation",
				"caret-cli/three-core-flows",
				"caret-cli/cli-reference",
				{
					type: "category",
					label: "サンプル",
					items: [
						"caret-cli/samples/overview",
						"caret-cli/samples/github-integration",
						"caret-cli/samples/github-issue-rca",
					],
				},
			],
		},
		*/
		{
			type: "category",
			label: "Caretツールの探索",
			items: [
				"exploring-carets-tools/caret-tools-guide",
				"exploring-carets-tools/document-tools",
				"exploring-carets-tools/new-task-tool",
				"exploring-carets-tools/remote-browser-support",
			],
		},
		{
			type: "category",
			label: "エンタープライズソリューション",
			items: [
				"enterprise-solutions/overview",
				"enterprise-solutions/cloud-provider-integration",
				"enterprise-solutions/custom-instructions",
				"enterprise-solutions/mcp-servers",
				"enterprise-solutions/security-concerns",
			],
		},
		{
			type: "category",
			label: "MCPサーバー",
			items: [
				"mcp/mcp-overview",
				"mcp/adding-mcp-servers-from-github",
				"mcp/configuring-mcp-servers",
				"mcp/connecting-to-a-remote-server",
				"mcp/mcp-marketplace",
				"mcp/mcp-server-development-protocol",
				"mcp/mcp-transport-mechanisms",
			],
		},
		{
			type: "category",
			label: "プロバイダー設定",
			items: [
				"provider-config/anthropic",
				"provider-config/claude-code",
				{
					type: "category",
					label: "AWS Bedrock",
					items: [
						"provider-config/aws-bedrock/api-key",
						"provider-config/aws-bedrock/iam-credentials",
						"provider-config/aws-bedrock/cli-profile",
					],
				},
				"provider-config/gcp-vertex-ai",
				"provider-config/litellm-and-caret-using-codestral",
				"provider-config/vscode-language-model-api",
				"provider-config/xai-grok",
				"provider-config/mistral-ai",
				"provider-config/baseten",
				"provider-config/fireworks-ai",
				"provider-config/deepseek",
				"provider-config/groq",
				"provider-config/cerebras",
				"provider-config/doubao",
				"provider-config/fireworks",
				"provider-config/zai",
				"provider-config/upstage",
				"provider-config/ollama",
				"provider-config/openai",
				"provider-config/openai-compatible",
				"provider-config/openrouter",
				"provider-config/sap-aicore",
				"provider-config/vercel-ai-gateway",
				"provider-config/requesty",
			],
		},
		{
			type: "category",
			label: "ローカルモデル実行",
			items: [
				"running-models-locally/read-me-first",
				"running-models-locally/overview",
				"running-models-locally/lm-studio",
				"running-models-locally/ollama",
			],
		},
		{
			type: "category",
			label: "トラブルシューティング",
			items: ["troubleshooting/terminal-quick-fixes", "troubleshooting/terminal-integration-guide"],
		},
		{
			type: "category",
			label: "詳細情報",
			items: ["more-info/telemetry"],
		},
	],
}

export default sidebars
