import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

const sidebars: SidebarsConfig = {
	tutorialSidebar: [
		{
			type: "category",
			label: "Getting Started",
			items: [
				"getting-started/what-is-caret",
				"getting-started/installing-caret",
				"getting-started/model-selection-guide",
				"getting-started/selecting-your-model",
				"getting-started/your-first-project",
				"getting-started/understanding-context-management",
				"getting-started/for-new-coders",
				"getting-started/task-management",
				"getting-started/installing-dev-essentials",
			],
		},
		{
			type: "category",
			label: "Introduction",
			items: ["introduction/overview", "introduction/welcome"],
		},
		{
			type: "category",
			label: "Improving Your Prompting Skills",
			items: ["prompting/prompt-engineering-guide", "prompting/caret-memory-bank"],
		},
		{
			type: "category",
			label: "Core Features",
			items: ["core-features/model-selection-guide"],
		},
		{
			type: "category",
			label: "Model Configuration",
			items: ["model-config/model-comparison", "model-config/context-windows"],
		},
		{
			type: "category",
			label: "Функции",
			items: [
				{
					type: "doc",
					id: "caret-exclusive/persona-system",
					label: "^ Система Персон",
				},
				{
					type: "doc",
					id: "caret-exclusive/dual-prompt-modes",
					label: "^ Система Dual Mode",
				},
				{
					type: "doc",
					id: "features/input-history",
					label: "^ История Промптов",
				},
				{
					type: "doc",
					id: "caret-exclusive/brand-switching",
					label: "^ OEM Переключение Бренда",
				},
				{
					type: "doc",
					id: "caret-exclusive/enhanced-provider-setup",
					label: "^ Расширенная Настройка",
				},
				{
					type: "doc",
					id: "caret-exclusive/caret-provider",
					label: "^ Провайдер Caret",
				},
				{
					type: "doc",
					id: "caret-exclusive/knowledge-parity-system",
					label: "^ Стандартизация ИИ",
				},
				{
					type: "doc",
					id: "caret-exclusive/document-tools",
					label: "^ Инструменты Документов",
				},
				{
					type: "doc",
					id: "caret-exclusive/image-tools",
					label: "^ Инструменты Изображений",
				},
				{
					type: "doc",
					id: "caret-exclusive/multilingual-ui",
					label: "^ Многоязычный UI",
				},
				"features/skills",
				"features/yolo-mode",
				"features/dictation",
				"features/multiroot-workspace",
				"features/drag-and-drop",
				"features/focus-chain",
				"features/plan-and-act",
				"features/auto-compact",
				"features/auto-approve",
				"features/checkpoints",
				"features/caret-rules",
				"features/editing-messages",
				"features/hooks",
				{
					type: "category",
					label: "@ Упоминания",
					items: [
						"features/at-mentions/overview",
						"features/at-mentions/file-mentions",
						"features/at-mentions/folder-mentions",
						"features/at-mentions/git-mentions",
						"features/at-mentions/problem-mentions",
						"features/at-mentions/terminal-mentions",
						"features/at-mentions/url-mentions",
					],
				},
				{
					type: "category",
					label: "Слеш-Команды",
					items: [
						"features/slash-commands/slash-commands",
						"features/slash-commands/deep-planning",
						"features/slash-commands/new-rule",
						"features/slash-commands/new-task",
						"features/slash-commands/report-bug",
						"features/slash-commands/smol",
						"features/slash-commands/workflows",
						"features/slash-commands/workflows/quickstart",
						"features/slash-commands/workflows/best-practices",
					],
				},
				{
					type: "category",
					label: "Команды и Горячие Клавиши",
					items: [
						"features/commands-and-shortcuts/overview",
						"features/commands-and-shortcuts/code-commands",
						"features/commands-and-shortcuts/git-integration",
						"features/commands-and-shortcuts/keyboard-shortcuts",
						"features/commands-and-shortcuts/terminal-integration",
					],
				},
				{
					type: "category",
					label: "Настройка",
					items: [
						"features/customization/opening-caret-in-sidebar",
						"features/customization/disable-terminal-pagers",
					],
				},
				{
					type: "category",
					label: "Задачи",
					items: ["features/tasks/understanding-tasks", "features/tasks/task-management"],
				},
			],
		},
		/* Caret CLI hidden for v0.4.4.
		{
			type: "category",
			label: "Caret CLI",
			items: [
				"caret-cli/overview",
				"caret-cli/installation",
				"caret-cli/three-core-flows",
				"caret-cli/cli-reference",
				{
					type: "category",
					label: "Samples",
					items: [
						"caret-cli/samples/overview",
						"caret-cli/samples/github-integration",
						"caret-cli/samples/github-issue-rca",
					],
				},
			],
		},
		*/
		{
			type: "category",
			label: "Exploring Caret's Tools",
			items: [
				"exploring-carets-tools/caret-tools-guide",
				"exploring-carets-tools/document-tools",
				"exploring-carets-tools/new-task-tool",
				"exploring-carets-tools/remote-browser-support",
			],
		},
		{
			type: "category",
			label: "Enterprise Solutions",
			items: [
				"enterprise-solutions/overview",
				"enterprise-solutions/cloud-provider-integration",
				"enterprise-solutions/custom-instructions",
				"enterprise-solutions/mcp-servers",
				"enterprise-solutions/security-concerns",
			],
		},
		{
			type: "category",
			label: "MCP Servers",
			items: [
				"mcp/mcp-overview",
				"mcp/adding-mcp-servers-from-github",
				"mcp/configuring-mcp-servers",
				"mcp/connecting-to-a-remote-server",
				"mcp/mcp-marketplace",
				"mcp/mcp-server-development-protocol",
				"mcp/mcp-transport-mechanisms",
			],
		},
		{
			type: "category",
			label: "Provider Configuration",
			items: [
				"provider-config/anthropic",
				"provider-config/claude-code",
				{
					type: "category",
					label: "AWS Bedrock",
					items: [
						"provider-config/aws-bedrock/api-key",
						"provider-config/aws-bedrock/iam-credentials",
						"provider-config/aws-bedrock/cli-profile",
					],
				},
				"provider-config/gcp-vertex-ai",
				"provider-config/litellm-and-caret-using-codestral",
				"provider-config/vscode-language-model-api",
				"provider-config/xai-grok",
				"provider-config/mistral-ai",
				"provider-config/fireworks-ai",
				"provider-config/deepseek",
				"provider-config/groq",
				"provider-config/cerebras",
				"provider-config/doubao",
				"provider-config/fireworks",
				"provider-config/zai",
				"provider-config/upstage",
				"provider-config/ollama",
				"provider-config/openai",
				"provider-config/openai-compatible",
				"provider-config/openrouter",
				"provider-config/sap-aicore",
				"provider-config/vercel-ai-gateway",
				"provider-config/requesty",
			],
		},
		{
			type: "category",
			label: "Running Models Locally",
			items: [
				"running-models-locally/read-me-first",
				"running-models-locally/overview",
				"running-models-locally/lm-studio",
				"running-models-locally/ollama",
			],
		},
		{
			type: "category",
			label: "Troubleshooting",
			items: ["troubleshooting/terminal-integration-guide"],
		},
		{
			type: "category",
			label: "More Info",
			items: ["more-info/telemetry"],
		},
	],
}

export default sidebars
